kind: ConfigMap
apiVersion: v1
data:
  client-header-buffer-size: 20m
  compute-full-forwarded-for: "true"
  forwarded-for-header: X-Forwarded-For
  large-client-header-buffers: 4 1024k
  proxy-body-size: 5000m
  use-forwarded-headers: "true"
  ssl-redirect: "false"
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
